/*
 * mpi_static.cpp - version MPI with static row distribution
 *
 * Compilation:
 *   mpic++ -o mpi_static mpi_static.cpp
 *
 * Usage:
 *   mpirun -np <P> ./mpi_static <M> <R> [seed]
 *
 *   <M>    : number of rows    (positive integer)
 *   <R>    : number of columns (positive integer)
 *   [seed] : optional random seed shared across versions
 *
 * Example:
 *   mpirun -np 4 ./mpi_static 1000 1000 12345
 */

#include <mpi.h>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdint>
#include <iostream>
#include <vector>

#ifdef _WIN32
#include <windows.h>
#endif

static const int MAX_VAL = 1000000000;
static const int MIN_VAL = 5000000;

// Global pointer for the local chunk of the matrix generated by each process.
// Each MPI rank will allocate `matrix` with space for its assigned rows
// (localRows * R) and fill it with deterministic values using
// `generateValue(seed, global_index)` so that the whole logical matrix
// is reproducible given the same `seed`.
static int* matrix = nullptr;


inline int generateValue(unsigned int seed, long long index)
{
    // Fast deterministic hash to generate value at specific index
    unsigned int x = seed ^ (index >> 32);
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    x ^= index & 0xFFFFFFFF;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    return MIN_VAL + (x % (MAX_VAL - MIN_VAL + 1));
}

// Build a local chunk of the global matrix: rows [startRow, startRow+rowCount)
// Implementation details:
// - `startRow` is the index of the first row in the global matrix that
//   this chunk corresponds to, calculated by rank.
// - `rowCount` is how many rows this process must generate.
// - `R` is the number of columns per row.
// - The function computes a `baseIndex = startRow * R` and then fills
//   the local linear buffer `matrix[0..rowCount*R-1]` with values
//   generated by `generateValue(seed, baseIndex + k)` for k in [0,total).
// - This avoids storing the whole global matrix on a single process and
//   allows each rank to independently reproduce the same values.
void buildMatrixChunk(int startRow, int rowCount, int R, unsigned int seed) {
    if (rowCount <= 0) return;
    long long baseIndex = (long long)startRow * R;
    long long total = (long long)rowCount * R;
    for (long long k = 0; k < total; ++k) {
        // map local offset k to the corresponding global linear index
        // and generate the deterministic value for that position
        matrix[k] = generateValue(seed, baseIndex + k);
    }
}



bool isPrime(int n)
{
    if (n < 2) return false;
    if (n == 2) return true;
    if (n % 2 == 0) return false;

    int raiz = static_cast<int>(std::sqrt(static_cast<double>(n)));
    for (int i = 3; i <= raiz; i += 2) {
        if (n % i == 0) return false;
    }
    return true;
}

//Old matrix calculation
// long long countPrimesInRowRange(int startRow, int rowCount, int R, unsigned int seed)
// {
//     long long count = 0;

//     // Generate and count primes row by row without storing matrix
//     long long baseIndex = (long long)startRow * R;
//     for (int i = 0; i < rowCount; ++i) {
//         for (int j = 0; j < R; ++j) {
//             int value = generateValue(seed, baseIndex + j);
//             if (isPrime(value)) {
//                 ++count;
//             }
//         }
//         baseIndex += R;
//     }

//     return count;
// }

int main(int argc, char* argv[])
{
#ifdef _WIN32
    SetConsoleOutputCP(CP_UTF8);
    SetConsoleCP(CP_UTF8);
#endif

    MPI_Init(&argc, &argv);

    int rank = 0;
    int size = 0;
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);

    if (argc != 3 && argc != 4) {
        if (rank == 0) {
            std::cerr << "\n[ERROR] Incorrect number of arguments.\n"
                      << "  Correct usage : mpirun -np <P> " << argv[0] << " <M> <R> [seed]\n"
                      << "  Example       : mpirun -np 4 " << argv[0] << " 1000 1000 12345\n\n";
        }
        MPI_Finalize();
        return 1;
    }

    int M = std::atoi(argv[1]);
    int R = std::atoi(argv[2]);
    unsigned int seed = (argc == 4) ? static_cast<unsigned int>(std::strtoul(argv[3], nullptr, 10)) : 12345u;

    if (M <= 0 || R <= 0) {
        if (rank == 0) {
            std::cerr << "\n[ERROR] M and R must be positive integers.\n"
                      << "  Received: M=" << argv[1] << "  R=" << argv[2] << "\n\n";
        }
        MPI_Finalize();
        return 1;
    }

    if (rank == 0) {
        std::cout << "-------------------------------------------------\n"
                  << " MPI STATIC VERSION - Prime count by rows\n"
                  << "-------------------------------------------------\n"
                  << " Rows    (M) : " << M << "\n"
                  << " Columns (R) : " << R << "\n"
                  << " Total elems  : " << static_cast<long long>(M) * R << "\n"
                  << " Value range  : [" << MIN_VAL << ", " << MAX_VAL << "]\n"
                  << " Processes    : " << size << "\n"
                  << " Seed         : " << seed << "\n"
                  << "-------------------------------------------------\n";
    }
    // Broadcast seed to all processes
    MPI_Bcast(&seed, 1, MPI_UNSIGNED, 0, MPI_COMM_WORLD);

    // Calculate local row range for this process
    int baseRows = M / size;
    int extraRows = M % size;
    int localRows = baseRows + (rank < extraRows ? 1 : 0);
    int startRow = rank * baseRows + std::min(rank, extraRows);

    if (rank == 0) {
        std::cout << "[INFO] Building matrix (each process generates its chunk)..." << std::flush;
    }

    // Measure local generation time
    double genStart = MPI_Wtime();
    double localGenMs = 0.0;
    if (localRows > 0) {
        matrix = new int[(size_t)localRows * R];
        buildMatrixChunk(startRow, localRows, R, seed);
    }
    double genEnd = MPI_Wtime();
    localGenMs = (genEnd - genStart) * 1000.0;

    // Synchronize before computation (single barrier)
    MPI_Barrier(MPI_COMM_WORLD);

    if (rank == 0) {
        std::cout << " done. (generated locally)\n";
    }

    // Measure local computation time (prime checking)
    double compStart = MPI_Wtime();
    long long localCount = 0;
    double localCompMs = 0.0;
    if (localRows > 0) {
        long long total = (long long)localRows * R;
        for (long long k = 0; k < total; ++k) {
            if (isPrime(matrix[k])) ++localCount;
        }
    }
    double compEnd = MPI_Wtime();
    localCompMs = (compEnd - compStart) * 1000.0;

    // Reduce local counts to total count at root
    long long totalCount = 0;
    MPI_Reduce(&localCount, &totalCount, 1, MPI_LONG_LONG, MPI_SUM, 0, MPI_COMM_WORLD);

    // Reduce timing statistics for generation
    double maxGenMs = 0.0, minGenMs = 0.0, sumGenMs = 0.0;
    MPI_Reduce(&localGenMs, &maxGenMs, 1, MPI_DOUBLE, MPI_MAX, 0, MPI_COMM_WORLD);
    MPI_Reduce(&localGenMs, &minGenMs, 1, MPI_DOUBLE, MPI_MIN, 0, MPI_COMM_WORLD);
    MPI_Reduce(&localGenMs, &sumGenMs, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);

    // Reduce timing statistics for computation
    double maxCompMs = 0.0, minCompMs = 0.0, sumCompMs = 0.0;
    MPI_Reduce(&localCompMs, &maxCompMs, 1, MPI_DOUBLE, MPI_MAX, 0, MPI_COMM_WORLD);
    MPI_Reduce(&localCompMs, &minCompMs, 1, MPI_DOUBLE, MPI_MIN, 0, MPI_COMM_WORLD);
    MPI_Reduce(&localCompMs, &sumCompMs, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);

    if (rank == 0) {
        double avgGenMs = sumGenMs / size;
        double avgCompMs = sumCompMs / size;
        std::cout << "-------------------------------------------------\n"
                  << " Prime numbers found : " << totalCount << "\n"
                  << " Generation time (max/min/avg) : " << maxGenMs << " / " << minGenMs << " / " << avgGenMs << " ms\n"
                  << " Computation time (max/min/avg): " << maxCompMs << " / " << minCompMs << " / " << avgCompMs << " ms\n"
                  << "-------------------------------------------------\n";
    }

    // Free local matrix chunk
    if (matrix) {
        delete[] matrix;
        matrix = nullptr;
    }

    // No matrix to delete - data generated
    double TOTAL = MPI_Wtime();
    std::cout << TOTAL << "------------------\n";
    MPI_Finalize();
    return 0;
}
